# Generated by Django 3.2.18 on 2023-04-07 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20230407_1452'),
        ('account', '0002_auto_20230407_1539'),
    ]

    operations = [
    ]
