# Generated by Django 4.1.7 on 2023-04-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_alter_inbodyimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='ChatGPTResponse',
            new_name='ExerciseResponse',
        ),
    ]
